@extends('layouts.plantilla')
@section('title', 'Rutas de '.$origen->nombre.' a '.$destino->nombre)
@section('estilos')<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">@endsection
@section('content')
<section class="container py-4"><header class="page-header"><a href="{{ route('home') }}" class="eyebrow">← Nueva búsqueda</a><h1 class="mt-2">{{ $origen->nombre }} → {{ $destino->nombre }}</h1><p>Opciones basadas en los servicios y horarios registrados.</p></header>
@if($itinerarios->isEmpty())<div class="empty-state content-card"><h2>No hay rutas disponibles</h2><p class="mb-0">Aún no hay una combinación registrada para este trayecto.</p></div>@else
<div id="route-map" class="rounded shadow-sm mb-4" style="height: 360px"></div><div class="row g-4">@foreach($itinerarios as $itinerario)<div class="col-12"><article class="content-card p-4"><div class="d-flex justify-content-between flex-wrap gap-2 mb-3"><div><p class="eyebrow mb-1">{{ $itinerario['transbordos'] ? $itinerario['transbordos'].' transbordo(s)' : 'Ruta directa' }}</p><h2 class="h4 mb-0">Salida {{ \Illuminate\Support\Str::of($itinerario['salida'])->substr(0,5) }} · llegada {{ \Illuminate\Support\Str::of($itinerario['llegada'])->substr(0,5) }}</h2></div></div><ol class="mb-0">@foreach($itinerario['tramos'] as $tramo)<li class="mb-3"><strong>{{ $tramo->origenMunicipio->nombre }} → {{ $tramo->destinoMunicipio->nombre }}</strong><br><span class="text-muted">{{ $tramo->nombre }} · {{ $tramo->categoria }} · {{ \Illuminate\Support\Str::of($tramo->hora_salida)->substr(0,5) }} – {{ \Illuminate\Support\Str::of($tramo->hora_llegada)->substr(0,5) }}@if($tramo->terminales->first()) · sale de {{ $tramo->terminales->first()->nombre }}@endif</span></li>@endforeach</ol></article></div>@endforeach</div>@endif</section>
@endsection
@section('scripts')@if($itinerarios->isNotEmpty())<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>const routes=@json($itinerarios->map(fn($item)=>collect($item['tramos'])->flatMap(fn($bus)=>[$bus->origenMunicipio,$bus->destinoMunicipio])->unique('id')->values()));const map=L.map('route-map');L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);const points=[];routes.forEach(route=>route.forEach(m=>{if(m.latitud!==null&&m.longitud!==null){const point=[Number(m.latitud),Number(m.longitud)];points.push(point);L.marker(point).addTo(map).bindPopup(m.nombre);}}));routes.forEach(route=>{const line=route.filter(m=>m.latitud!==null&&m.longitud!==null).map(m=>[Number(m.latitud),Number(m.longitud)]);if(line.length>1)L.polyline(line,{color:'#0d6efd'}).addTo(map);});if(points.length)map.fitBounds(points,{padding:[30,30]});else map.setView([12.8654,-85.2072],7);</script>@endif@endsection
